name: ETF Scanner

on:
  workflow_run:
    workflows:
      - NSE Daily Bhavcopy
    types:
      - completed

  workflow_dispatch:

jobs:
  scan:
    if: >
      github.event_name == 'workflow_dispatch' ||
      (
        github.event.workflow_run.conclusion == 'success' &&
        github.event.workflow_run.head_branch == 'main'
      )

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check Google Sheet secrets
        env:
          GOOGLE_SPREADSHEET_ID: ${{ secrets.GOOGLE_SPREADSHEET_ID }}
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        run: |
          if [ -z "$GOOGLE_SPREADSHEET_ID" ]; then
            echo "ERROR: GOOGLE_SPREADSHEET_ID is EMPTY"
            exit 1
          fi

          if [ -z "$GOOGLE_SERVICE_ACCOUNT_JSON" ]; then
            echo "ERROR: GOOGLE_SERVICE_ACCOUNT_JSON is EMPTY"
            exit 1
          fi

          echo "Google Sheet credentials are available."

      - name: Run ETF Scanner
        env:
          GOOGLE_SPREADSHEET_ID: ${{ secrets.GOOGLE_SPREADSHEET_ID }}
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        run: |
          python etf_scanner.py
